#!/usr/bin/env bash

# curl + pretty printing with bat & jq. Also prints the method and URL.
# Assumes URL is the last parameter.
# I use it for scripts using curl, not when using curl directly in the terminal,
# since there I can see the used URL and a "| bat" is good enough.

# Let the script fail on error and on failing pipes
set -eo pipefail

args=("$@")
method="GET"

for i in "${!args[@]}"; do
    if [ "${args[$i]}" = "-X" ]; then
        method="${args[$((i+1))]}"
    fi
done

printf "\e[1m%s\e[0m %s\n" "$method" "${@:$#}"
result="$(curl "$@")";

if [ "${result:0:5}" == "HTTP/" ]; then
    # curl was likely invoked with -i, so try to detect the body
    # and format it with jq, if it's json.
    is_headers=true
    # collect lines in arrays
    header_lines=()
    body_lines=()
    while IFS= read -r line; do 
        if [ -n "$(echo "$line" | sed -n '/^[[:space:]]*$/p')" ]; then 
            is_headers=false
        else
            if $is_headers; then
                header_lines+=("$line")
            else    
                body_lines+=("$line")
            fi
        fi
    done <<< "$result"

    header=$(printf "%s\n" "${header_lines[@]}")
    body=$(printf "%s\n" "${body_lines[@]}")

    set +e
    is_json=$(jq -re '""' <<<"${body}" 2>&1)
    set -e

    formatted="${header}"
    if [ -z "${is_json}" ]; then
        formatted="${formatted}"$'\n'$'\n'"$(echo "$body" | jq .)"
    else
        formatted="${formatted}"$'\n'$'\n'"${body}"
        echo "$result" | bat --style=numbers,grid
    fi
    echo "$formatted" | bat --style=numbers,grid
else
    # Seems to be just the body ...
    set +e
    is_json=$(jq -re '""' <<<"${result}" 2>&1)
    set -e

    if [ -z "${is_json}" ]; then
        echo "$result" | jq . | bat -l json --style=numbers,grid
    else
        echo "$result" | bat --style=numbers,grid
    fi
fi
