#!/usr/bin/env bash
if [[ -z $1 ]] || [[ $1 == "-" ]]; then
    input=$(mktemp)
    trap "rm -f $input" EXIT
    cat /dev/stdin > $input
else
    input=$1
fi

# header is acting as like a cheatsheet
header=$'{ contains: [.items[] | select(contains("jq"))], slice: .items[-3:], b64: (.token | @base64d) }\nCTRL+S to save output, CTRL+O to include query'
if [[ -n ${IJQ_HISTFILE:-} ]]; then
    header+=', CTRL+N/P to cycle query history'
fi

echo '' \
    | fzf --phony \
          --query "${2-.}" \
          --preview-window='up:99%' \
          --prompt 'jq ' \
          --header "$header" \
          --header-lines 2 \
          --print-query \
          --no-info \
          --preview-border 'bottom' \
          --padding '1,1,0,1' \
          --highlight-line \
          --pointer='󰙎' \
          ${IJQ_HISTFILE:+--history=$IJQ_HISTFILE} \
          --marker='' \
          --preview "jq --color-output -r {q} $input" \
          --bind "ctrl-s:execute-silent(jq --monochrome-output -r {q} \"$input\" > \"ijq-\$(date +%Y%m%d-%H%M%S).json\")" \
          --bind "ctrl-o:execute-silent({ printf '// %s\n' {q}; jq --monochrome-output -r {q} \"$input\"; } > \"ijq-\$(date +%Y%m%d-%H%M%S).jsonc\")"
